steps:
- name: 'node:14'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    npm run build -- --prod
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', 'dist/angular-demo/', 'gs://maaz-bucket']

options:
  logging: CLOUD_LOGGING_ONLY
