steps:
- name: 'node:20'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    npm install -g @angular/cli
    npm install
    npm run build -- --configuration production
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', 'dist/angular-demo/', 'gs://maaz-bucket']

options:
  logging: CLOUD_LOGGING_ONLY
